name: bara_flutter
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  google_fonts: ^6.2.1
  intl: ^0.20.1
  logging: ^1.3.0
  nfc_manager: ^3.5.0
  path_provider: ^2.1.5
  shared_preferences: ^2.3.5
  supabase_auth_ui: ^0.5.4
  supabase_flutter: ^2.8.3
  uuid: ^4.5.1
  watch_it: ^1.6.2

dev_dependencies:
  build_runner: ^2.4.14
  flutter_launcher_icons: ^0.14.2
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - .env

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icon/adaptive-icon.png"
