name: bara_flutter
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  intl: ^0.20.1
  path_provider: ^2.1.5
  shared_preferences: ^2.3.5
  supabase_flutter: ^2.8.3
  watch_it: ^1.6.2

dev_dependencies:
  build_runner: ^2.4.14
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - .env
